const Student = require('../models/Student');
const Course = require('../models/Course');
const Enquiry = require('../models/Enquiry');
const Communication = require('../models/Communication');

// @desc    Create new student with auto-updates
// @route   POST /api/students
// @access  Private
exports.createStudent = async (req, res) => {
  try {
    const { fullName, email, phone, dateOfBirth, gender, course, year, semester, enquiryId } = req.body;

    // Basic validation
    if (!fullName || !email || !phone || !dateOfBirth || !gender || !course || !year || !semester) {
      return res.status(400).json({
        success: false,
        message: 'Please provide all required fields'
      });
    }

    // Check if email already exists
    const existingStudent = await Student.findOne({ email });
    if (existingStudent) {
      return res.status(400).json({
        success: false,
        message: 'A student with this email already exists'
      });
    }

    // Find course by name to update seats
    const courseDoc = await Course.findOne({ courseName: course });
    
    if (courseDoc) {
      // Check if seats are available
      if (courseDoc.seats.available <= 0) {
        return res.status(400).json({
          success: false,
          message: `No seats available in ${course}. All ${courseDoc.seats.total} seats are filled.`
        });
      }
      
      // Update course seats
      courseDoc.seats.filled += 1;
      courseDoc.seats.available = courseDoc.seats.total - courseDoc.seats.filled;
      await courseDoc.save();
      
      console.log(`✅ Course seats updated: ${course} - Filled: ${courseDoc.seats.filled}/${courseDoc.seats.total}`);
    }

    // Create student (studentId will be auto-generated by pre-save hook)
    const student = await Student.create(req.body);

    // If linked to enquiry, update enquiry status to "Admitted"
    if (enquiryId) {
      const enquiry = await Enquiry.findByIdAndUpdate(
        enquiryId,
        { status: 'Admitted' },
        { new: true }
      );
      
      if (enquiry) {
        console.log(`✅ Enquiry status updated to "Admitted": ${enquiry.studentName}`);
        
        // Auto-create communication log
        await Communication.create({
          enquiryId: enquiryId,
          studentId: student._id,
          communicationType: 'In-person Meeting',
          subject: 'Student Admission Completed',
          notes: `Student ${fullName} has been successfully admitted to ${course}. Student ID: ${student.studentId}`,
          followUpRequired: false,
          recordedBy: req.admin._id,
          recordedByName: req.admin.fullName || 'System'
        });
        
        console.log(`✅ Communication log created for admission`);
      }
    } else {
      // Even without enquiry link, create a communication log
      await Communication.create({
        studentId: student._id,
        communicationType: 'In-person Meeting',
        subject: 'Direct Student Admission',
        notes: `Student ${fullName} has been directly admitted to ${course}. Student ID: ${student.studentId}`,
        followUpRequired: false,
        recordedBy: req.admin._id,
        recordedByName: req.admin.fullName || 'System'
      });
      
      console.log(`✅ Communication log created for direct admission`);
    }

    res.status(201).json({
      success: true,
      message: 'Student created successfully. Course seats and enquiry status updated automatically.',
      data: student,
      automation: {
        courseSeatsUpdated: courseDoc ? true : false,
        enquiryStatusUpdated: enquiryId ? true : false,
        communicationLogCreated: true
      }
    });
  } catch (error) {
    console.error('Create student error:', error);
    
    // Handle duplicate email error
    if (error.code === 11000) {
      return res.status(400).json({
        success: false,
        message: 'Email already exists'
      });
    }

    // Handle validation errors
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map(err => err.message);
      return res.status(400).json({
        success: false,
        message: messages.join(', ')
      });
    }

    res.status(500).json({
      success: false,
      message: 'Error creating student',
      error: error.message
    });
  }
};

// @desc    Get all students
// @route   GET /api/students
// @access  Private
exports.getAllStudents = async (req, res) => {
  try {
    const { 
      status, 
      course, 
      year, 
      semester,
      search, 
      page = 1, 
      limit = 10, 
      sortBy = 'admissionDate', 
      order = 'desc' 
    } = req.query;

    // Build query
    const query = {};

    if (status) {
      query.status = status;
    }

    if (course) {
      query.course = course;
    }

    if (year) {
      query.year = parseInt(year);
    }

    if (semester) {
      query.semester = parseInt(semester);
    }

    if (search) {
      query.$or = [
        { fullName: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { studentId: { $regex: search, $options: 'i' } },
        { phone: { $regex: search, $options: 'i' } }
      ];
    }

    // Calculate pagination
    const skip = (page - 1) * limit;
    const sortOrder = order === 'asc' ? 1 : -1;

    // Execute query
    const students = await Student.find(query)
      .populate('enquiryId', 'studentName email phone')
      .sort({ [sortBy]: sortOrder })
      .skip(skip)
      .limit(parseInt(limit));

    const total = await Student.countDocuments(query);

    res.json({
      success: true,
      data: students,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    console.error('Get students error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching students',
      error: error.message
    });
  }
};

// @desc    Get student by ID
// @route   GET /api/students/:id
// @access  Private
exports.getStudentById = async (req, res) => {
  try {
    const student = await Student.findById(req.params.id)
      .populate('enquiryId', 'studentName email phone courseApplied');

    if (!student) {
      return res.status(404).json({
        success: false,
        message: 'Student not found'
      });
    }

    res.json({
      success: true,
      data: student
    });
  } catch (error) {
    console.error('Get student error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching student',
      error: error.message
    });
  }
};

// @desc    Update student
// @route   PUT /api/students/:id
// @access  Private
exports.updateStudent = async (req, res) => {
  try {
    const student = await Student.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    );

    if (!student) {
      return res.status(404).json({
        success: false,
        message: 'Student not found'
      });
    }

    res.json({
      success: true,
      message: 'Student updated successfully',
      data: student
    });
  } catch (error) {
    console.error('Update student error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating student',
      error: error.message
    });
  }
};

// @desc    Delete student (with course seat auto-adjustment)
// @route   DELETE /api/students/:id
// @access  Private
exports.deleteStudent = async (req, res) => {
  try {
    const student = await Student.findById(req.params.id);

    if (!student) {
      return res.status(404).json({
        success: false,
        message: 'Student not found'
      });
    }

    // Find and update course seats
    const courseDoc = await Course.findOne({ courseName: student.course });
    
    if (courseDoc) {
      courseDoc.seats.filled = Math.max(0, courseDoc.seats.filled - 1);
      courseDoc.seats.available = courseDoc.seats.total - courseDoc.seats.filled;
      await courseDoc.save();
      
      console.log(`✅ Course seats updated after deletion: ${student.course} - Filled: ${courseDoc.seats.filled}/${courseDoc.seats.total}`);
    }

    // Delete the student
    await Student.findByIdAndDelete(req.params.id);

    res.json({
      success: true,
      message: 'Student deleted successfully. Course seats updated.',
      automation: {
        courseSeatsUpdated: courseDoc ? true : false
      }
    });
  } catch (error) {
    console.error('Delete student error:', error);
    res.status(500).json({
      success: false,
      message: 'Error deleting student',
      error: error.message
    });
  }
};

// @desc    Update student status
// @route   PATCH /api/students/:id/status
// @access  Private
exports.updateStudentStatus = async (req, res) => {
  try {
    const { status } = req.body;

    if (!status) {
      return res.status(400).json({
        success: false,
        message: 'Status is required'
      });
    }

    const student = await Student.findByIdAndUpdate(
      req.params.id,
      { status },
      { new: true, runValidators: true }
    );

    if (!student) {
      return res.status(404).json({
        success: false,
        message: 'Student not found'
      });
    }

    res.json({
      success: true,
      message: 'Status updated successfully',
      data: student
    });
  } catch (error) {
    console.error('Update status error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating status',
      error: error.message
    });
  }
};